// @ont/cli — B5 surface (the `ont` CLI, clean-build). See docs/core/B5_CLI_CLASSIFICATION.md. A thin operator
// orchestrator: consumes L1-L4 APIs, reimplements no rules, holds no keys, never signs (signing → B5-WALLET).
// First slice = the read commands (get-value-history / get-recovery-descriptor-history / get-tx) over an
// injected CliReadPort.
export { type CliReadPort, type CliTxRead, type ResolverRawRead, type ResolverRawQuery } from "./read-port.js";
export {
  shapeReadQuery,
  shapeNameQuery,
  shapeTxidQuery,
  shapeRawReadQuery,
  type ReadCommand,
  type ReadQuery,
  type NameQuery,
  type TxidQuery,
  type RawReadCommand,
  type RawReadQuery,
  type ShapeRejectReason,
} from "./shape-read-query.js";
export {
  renderValueHistory,
  renderRecoveryHistory,
  renderTx,
  renderResolverRaw,
  type HistoryView,
  type TxView,
  type RawView,
  type RenderHistoryResult,
  type RenderTxResult,
  type RenderResolverRawResult,
} from "./render-read.js";
export {
  renderRecoveryWalletProofMessage,
  runVerifyRecoveryWalletProof,
  runInspectProofBundle,
  runVerifyProofBundleAgainstBitcoin,
  SIGNET_LAUNCH_HEADER_SOURCE_ID,
  buildSignetLaunchHeaderSourceFromHeaders,
  createEsploraHeaderRangeProvider,
  createResolverHeaderRangeProvider,
  fetchSignetLaunchHeaderSource,
  proofBundleMaxAnchorHeight,
  signetLaunchHeaderRange,
  type RecoveryWalletProofMessageFields,
  type VerifyRecoveryWalletProofInput,
  type VerifyProofBundleAgainstBitcoinInput,
  type BuildSignetLaunchHeaderSourceInput,
  type CanonicalHeaderRejectReason,
  type CanonicalHeaderResult,
  type FetchSignetLaunchHeaderSourceInput,
  type HeaderRangeProvider,
  type EsploraHeaderRangeProviderOptions,
  type ResolverHeaderRangeProviderOptions,
  type SignetLaunchHeaderRangeInput,
  type SignetLaunchHeaderRangeResult,
  type RenderMessageResult,
  type VerifyWalletProofResult,
  type InspectProofBundleResult,
  type VerifyProofBundleAgainstBitcoinResult,
} from "./verify-commands.js";
export {
  ONT_BITCOIN_HEADER_SOURCE_ENV,
  ONT_ESPLORA_URL_ENV,
  ONT_HEADER_PROVIDER_ENV,
  ONT_RESOLVER_URL_ENV,
  createResolverNameProofBundleSource,
  renderCliVerifyNameResult,
  runOntCli,
  selectCliVerifyResolverUrl,
  selectCliVerifyHeaderProvider,
  verifyNameAgainstResolver,
  type CliVerifyNameResult,
  type ResolverNameProofBundleSource,
} from "./live-verify.js";
